### ISSUE TITLE
Make a JS API

### ISSUE THREAD

**Issue by Haroenv** [algolia/talksearch-embed#15]
1. make the iframe
2. set `allowfullscreen`
2. communicate with it
3. make sure the height is complete (see [link](https://blog.rnsloan.com/2013/08/14/calculating-the-height-of-an-iframe/) and https://github.com/algolia/talksearch/issues/27#issuecomment-352070319)
5. have some kind of url sync behaviour
6. get index metadata

Possible API (I'm not convinced about the names)

```js
import { allVideos, singleVideo } from 'talksearch';

const videoInterface = allVideos({
  indexName: '',
  // affiliation: true,
  selector: '#talksearch',
  stylesheets: ['https://example.com/extra.css'],
  urlSync: false,
});

videoInterface
  .getMetaData()
  .then(({ name, image, ...others }) => console.log('received'));

videoInterface.destroy();

const video = singleVideo({
  indexName: '',
  videoId: '',
  selector: '#that-one-vid',
});

video.getMetaData().then(console.log);

video.destroy();
```

**Comment by vvo** [comment]
Reference comment with proposed API: https://github.com/algolia/talksearch/issues/6#issuecomment-350226787

@Haroenv can you make a detailed proposal API along with some implementations details (iframe with or without actual url)

**Comment by Haroenv** [comment]
I’m not sure why we want to avoid using an IFrame, on bigger sites, styling will be quite hard without an IFrame, and it’s easier to load async

**Comment by vvo** [comment]
Your call, you can wait to have the issue raised to effectively propose to not have an iframe. It's fine also.

Still it's always good to start with an API proposal and iterate
